### PR TITLE
Added support for sending a funny GIF reply when a related word is sent

### LINKED ISSUE #44: Send funny GIF when the word "romo" is typed

### PR DESCRIPTION
**Pull request by francisbrito**
Matches: *beer, birra, booze, romo*
Replies with: [GIF](https://media.giphy.com/media/cC9nMt8P3gsUVka1Ul/giphy.gif)

Closes #44

### CODE REVIEW

**Comment by francisbrito** [comment]
Hey @kengru,

It seems Travis CI is missing `SPOTIPY`-related configuration, is there any change it could be added?

**Comment by ronyb29** [comment]
Sure, I'll get on it tonight.

I remember I started setting up automatic deployments when tests passed
too, but didn't finish. Maybe I'll fix that too.

**Comment by ronyb29** [comment]
@francisbrito looks like you'll have to set up the secrets in travis for your branch
https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions

These are the required secrets
image

**Comment by francisbrito** [comment]
I see, from the docs it seems this restriction only happens to PRs. I'll push my branch directly to this repo then. Thanks for reaching out

**Pull request closed without merging**
